import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

test('router exposes the ai coach route', () => {
  const router = fs.readFileSync('src/router/index.js', 'utf8')
  const view = fs.readFileSync('src/views/AICoach.vue', 'utf8')

  assert.match(router, /path:\s*'\/coach'/)
  assert.match(router, /name:\s*'AICoach'/)
  assert.match(router, /component:\s*\(\)\s*=>\s*import\(['"]@\/views\/AICoach\.vue['"]\)/)
  assert.match(router, /title:\s*'AI 学习教练'/)
  assert.match(router, /requiresAuth:\s*true/)

  assert.match(view, />\s*学习画像表单\s*</)
  assert.match(view, />\s*今日计划卡片\s*</)
  assert.match(view, />\s*当前阶段进度\s*</)
  assert.match(view, />\s*复盘结果区\s*</)
  assert.match(view, />\s*工作流日志\s*</)
  assert.match(view, /本轮完成度摘要/)
  assert.match(view, /coachStore\.generateDailyPlan\(/)
  assert.match(view, /已生成今日计划，可直接进入学习模式。/)
  assert.match(view, /const summaryMetrics = computed\(/)
  assert.match(view, /const learnedRecommendedCount = computed\(/)
  assert.match(view, /const completedTaskCount = computed\(/)
  assert.match(view, /primaryAction\.description/)
  assert.match(view, /v-for="metric in summaryMetrics"/)
  assert.match(view, /coachStore\.dailyPlan\.sessionTitle/)
  assert.match(view, /coachStore\.dailyPlan\.coachTip/)
  assert.match(view, /v-for="task in coachStore\.dailyPlan\.tasks"/)
  assert.match(view, /task\.done \? '已完成' : '待完成'/)
  assert.match(view, /v-for="word in coachStore\.dailyPlan\.recommendedWords"/)
  assert.match(view, /coachStore\.activeRun\?\.currentStage/)
  assert.match(view, /coachStore\.activeRun\?\.status/)
  assert.match(view, /const stageProgressSteps = computed\(/)
  assert.match(view, /const primaryAction = computed\(/)
  assert.match(view, /v-for="step in stageProgressSteps"/)
  assert.match(view, /primaryAction\.label/)
  assert.match(view, /handlePrimaryAction\(/)
  assert.match(view, /v-for="event in coachStore\.runEvents"/)
  assert.match(view, /formatEventType\(/)
  assert.match(view, /formatEventTime\(/)
  assert.match(view, /formatEventPayload\(/)
  assert.match(view, /event\.inputJson \|\| event\.input_json/)
  assert.match(view, /event\.outputJson \|\| event\.output_json/)
  assert.match(view, /const canGeneratePlan = computed\(/)
  assert.match(view, /const canGenerateQuiz = computed\(/)
  assert.match(view, /const canSummarizeReflection = computed\(/)
  assert.match(view, /:disabled="!canGeneratePlan"/)
  assert.match(view, /:disabled="!canGenerateQuiz"/)
  assert.match(view, /:disabled="!canSummarizeReflection"/)
  assert.match(view, /to="\/study"/)

  assert.doesNotMatch(view, /计划生成功能仍是占位壳层/)
  assert.doesNotMatch(view, /<pre>\{\{ coachStore\.dailyPlan \}\}<\/pre>/)
  assert.doesNotMatch(view, /<pre>\{\{ coachStore\.activeRun \}\}<\/pre>/)
  assert.doesNotMatch(view, /计划测验/)
  assert.doesNotMatch(view, /已完成步骤/)
  assert.doesNotMatch(view, /沉淀复盘结论/)
})
