import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

test('supabase schema includes ai workflow tables', () => {
  const sql = fs.readFileSync('supabase-schema.sql', 'utf8')
  assert.match(sql, /CREATE TABLE IF NOT EXISTS user_ai_profiles/i)
  assert.match(sql, /CREATE TABLE IF NOT EXISTS learning_workflow_runs/i)
  assert.match(sql, /CREATE TABLE IF NOT EXISTS learning_workflow_events/i)
  assert.match(sql, /CREATE INDEX IF NOT EXISTS idx_learning_workflow_runs_user_id ON learning_workflow_runs\(user_id\)/i)
  assert.match(sql, /CREATE INDEX IF NOT EXISTS idx_learning_workflow_events_run_id ON learning_workflow_events\(run_id\)/i)
  assert.match(sql, /CREATE INDEX IF NOT EXISTS idx_learning_workflow_events_run_created_at_id ON learning_workflow_events\(run_id,\s*created_at,\s*id\)/i)
  assert.match(sql, /ALTER TABLE user_ai_profiles ENABLE ROW LEVEL SECURITY/i)
  assert.match(sql, /ALTER TABLE learning_workflow_runs ENABLE ROW LEVEL SECURITY/i)
  assert.match(sql, /ALTER TABLE learning_workflow_events ENABLE ROW LEVEL SECURITY/i)
  assert.match(sql, /CREATE POLICY "Users can update own workflow runs"[\s\S]*?ON learning_workflow_runs[\s\S]*?FOR UPDATE[\s\S]*?auth\.uid\(\) = user_id/i)
  assert.match(sql, /CREATE POLICY "Users can view own workflow events"[\s\S]*?ON learning_workflow_events[\s\S]*?FOR SELECT[\s\S]*?FROM learning_workflow_runs[\s\S]*?learning_workflow_runs\.user_id = auth\.uid\(\)/i)
  assert.match(sql, /CREATE POLICY "Users can insert own workflow events"[\s\S]*?ON learning_workflow_events[\s\S]*?FOR INSERT[\s\S]*?FROM learning_workflow_runs[\s\S]*?learning_workflow_runs\.user_id = auth\.uid\(\)/i)
  assert.doesNotMatch(sql, /CREATE POLICY "Users can delete own workflow runs"/i)
  assert.doesNotMatch(sql, /CREATE POLICY "Users can delete own workflow events"/i)
  assert.match(sql, /CREATE TRIGGER update_user_ai_profiles_updated_at[\s\S]*?BEFORE UPDATE ON user_ai_profiles/i)
  assert.match(sql, /CREATE TRIGGER update_learning_workflow_runs_updated_at[\s\S]*?BEFORE UPDATE ON learning_workflow_runs/i)
})

test('supabase client exports ai profile and workflow helpers', () => {
  const content = fs.readFileSync('src/utils/supabase.js', 'utf8')
  assert.match(content, /export const aiProfiles =/)
  assert.match(content, /export const workflowRuns =/)
  assert.match(content, /export const workflowEvents =/)
  assert.doesNotMatch(content, /getProfile\(payload\.user_id\)/)
  assert.match(content, /async upsertProfile\(payload\)[\s\S]*?\.from\('user_ai_profiles'\)[\s\S]*?\.update\(payload\)[\s\S]*?\.eq\('user_id', payload\.user_id\)[\s\S]*?\.select\(\)[\s\S]*?\.maybeSingle\(\)/)
  assert.match(content, /if\s*\(\s*updatedProfile\s*\|\|\s*updateError\s*\)[\s\S]*?return/)
  assert.match(content, /const\s*\{\s*data:\s*insertedProfile,\s*error:\s*insertError\s*\}\s*=\s*await supabase[\s\S]*?\.from\('user_ai_profiles'\)[\s\S]*?\.insert\(payload\)[\s\S]*?\.select\(\)[\s\S]*?\.single\(\)/)
  assert.match(content, /if\s*\(\s*!insertError\s*\|\|\s*!isUniqueConstraintError\(insertError\)\s*\)[\s\S]*?return/)
  assert.match(content, /return supabase[\s\S]*?\.from\('user_ai_profiles'\)[\s\S]*?\.update\(payload\)[\s\S]*?\.eq\('user_id', payload\.user_id\)[\s\S]*?\.select\(\)[\s\S]*?\.single\(\)/)
  assert.doesNotMatch(content, /\.upsert\(payload,\s*\{\s*onConflict:\s*'user_id'\s*\}\)/)
  assert.match(content, /const WORKFLOW_RUN_FIELD_MAP = \{/)
  assert.match(content, /currentStage:\s*'current_stage'/)
  assert.match(content, /planJson:\s*'plan_json'/)
  assert.match(content, /reflectionJson:\s*'reflection_json'/)
  assert.match(content, /startedAt:\s*'started_at'/)
  assert.match(content, /completedAt:\s*'completed_at'/)
  assert.match(content, /async createRun\(payload\)[\s\S]*?serializeWorkflowRunPayload\(payload\)[\s\S]*?\.from\('learning_workflow_runs'\)[\s\S]*?\.insert\(serializedPayload\)[\s\S]*?\.select\(\)[\s\S]*?\.single\(\)/)
  assert.match(content, /async getLatestRun\(userId\)/)
  assert.match(content, /\.from\('learning_workflow_runs'\)[\s\S]*?\.eq\('user_id', userId\)[\s\S]*?\.order\('created_at', \{ ascending: false \}\)[\s\S]*?\.limit\(1\)[\s\S]*?\.maybeSingle\(\)/)
  assert.match(content, /async getRunById\(runId\)/)
  assert.match(content, /\.from\('learning_workflow_runs'\)[\s\S]*?\.eq\('id', runId\)[\s\S]*?\.maybeSingle\(\)/)
  assert.match(content, /async updateRun\(runId,\s*payload\)/)
  assert.match(content, /async updateRun\(runId,\s*payload\)[\s\S]*?serializeWorkflowRunPayload\(payload\)[\s\S]*?\.from\('learning_workflow_runs'\)[\s\S]*?\.update\(serializedPayload\)[\s\S]*?\.eq\('id', runId\)[\s\S]*?\.select\(\)[\s\S]*?\.single\(\)/)
  assert.match(content, /async getRunEvents\(runId\)/)
  assert.match(content, /\.from\('learning_workflow_events'\)[\s\S]*?\.eq\('run_id', runId\)[\s\S]*?\.order\('created_at', \{ ascending: true \}\)[\s\S]*?\.order\('id', \{ ascending: true \}\)/)
  assert.match(content, /async addEvent\(payload\)/)
  assert.match(content, /\.from\('learning_workflow_events'\)[\s\S]*?\.insert\(payload\)[\s\S]*?\.select\(\)[\s\S]*?\.single\(\)/)
})
